### ISSUE TITLE
List index out of range

### ISSUE THREAD

**Issue by quintendewilde** [atif93/google_image_downloader#2]
Hi found this from the stackoverflow post. 

And when I tried to run it It gave me this error. 
```

 Traceback (most recent call last):
  File "image_download.py", line 73, in <module>
    main()
  File "image_download.py", line 15, in main
    num_requested = int(sys.argv[2])
IndexError: list index out of range

```
Is it broken or I'm I missing something?

**Comment by atif93** [comment]
Hi, 

Did you run the script as `python image_download.py <query> <number of images>`?
You have to provide both the `<query>` to be searched for and the `<number of images>` to be downloaded.

**Comment by ubaidsworld** [comment]
@BLCKPSTV  How you have initiated your program? Is that exactly the way mentioned in the READ.ME file of the repository?
Kindly share. This issue is because you have inited the program wrongly.
You might have tried query like this:  `python image_download.py <query>` and missed the number of images field or you might have missed the query field or you missed both.
Try the way mentioned in the Read.me file and let me know.
